version: "3.8"

services:
  imaginary:
    image: h2non/imaginary
    command: -concurrency 20 -enable-url-source -allowed-origins https://lain.bgm.tv
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.imaginary.rule=PathPrefix(`/resize`, `/smartcrop`)"
      - "traefik.http.routers.imaginary.entrypoints=web"
    ports:
      - '9000:9000'

  minio:
    image: "minio/minio:RELEASE.2022-08-13T21-54-44Z.fips"
    container_name: "chii-base-minio"
    command: "server /mnt/ --address=0.0.0.0:9001 --console-address=0.0.0.0:9002"
    restart: unless-stopped
    ports:
      - "9002:9002"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minio-root"
      MINIO_ROOT_PASSWORD: "minio-root-password"
      MINIO_PROMETHEUS_AUTH_TYPE: public
    volumes:
      - "./data/minio:/mnt"
