version: "3.8"

services:
  http-gateway:
    container_name: "chii-app-img-proxy"
    image: ghcr.io/bangumi/img-proxy:latest
    command:
      - --upstream
      - http://traefik
      - --s3.entrypoint
      - minio:9000
      - --s3.access-key
      - ...
      - --s3.secret-key
      - ...
    ports:
      - "127.0.0.1:8003:8003"
    volumes:
      - /home/ubuntu/img-cache/:/img-cache/
    environment:
      HTTP_HOST: "0.0.0.0"
      HTTP_PORT: "8003"

  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "9080:80"
      - "9002:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  imaginary:
    image: h2non/imaginary
    command: -cors -gzip -concurrency 20 -enable-url-source -allowed-origins https://lain.bgm.tv
    # noinspection ComposeUnknownKeys
    deploy:
      replicas: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.imaginary.rule=PathPrefix(`/resize`, `/smartcrop`)"
      - "traefik.http.routers.imaginary.entrypoints=web"
    expose:
      - '9000'

  minio:
    image: "minio/minio:RELEASE.2022-08-13T21-54-44Z.fips"
    container_name: "chii-base-minio"
    command: "server /mnt/"
    restart: unless-stopped
    expose:
      - 9000
    ports:
      - "127.0.0.1:8999:8999"
      - "127.0.0.1:9000:9000"
    environment:
      MINIO_ROOT_USER: "..."
      MINIO_ROOT_PASSWORD: "..."
      MINIO_PROMETHEUS_AUTH_TYPE: public
    volumes:
      - "...:/mnt"
