name: release

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true

      - run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - run: go build -o dist/img-proxy -trimpath -ldflags "-X 'main.version=$(git describe --match='v*' --tags)'"
        name: Build Binary
        env:
          CGO_ENABLED: '0'

      - run: docker build -t ghcr.io/bangumi/img-proxy:${{env.TAG}} .

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - run: docker push ghcr.io/bangumi/img-proxy:${{env.TAG}}

      - name: push latest tag
        if: "${{ startsWith(github.ref, 'refs/tags/') }}"
        run: |
          docker tag ghcr.io/bangumi/img-proxy:${{env.TAG}} ghcr.io/bangumi/img-proxy:latest
          docker push ghcr.io/bangumi/img-proxy:latest
