name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          check-latest: true

      - name: Go Build Cache (build)
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg
          key: go-cache-119-${{ hashFiles('**/go.sum') }}-build
          restore-keys: |
            go-cache-119-${{ hashFiles('**/go.sum') }}-

      - run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - run: go build -o dist/img-proxy -ldflags "-X 'main.version=$(git describe --match='v*')'"
        name: Build Binary

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./
          file: Dockerfile
          tags: ghcr.io/bangumi/img-proxy:latest,ghcr.io/bangumi/img-proxy:${{env.TAG}}
