name: release

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: trim21/actions/setup-go@master

      - run: echo "SHA=$(git show --no-patch --no-notes --date=short-local --pretty='%as-%h')" >> $GITHUB_ENV
        env:
          TZ: UTC

      - run: go build -o dist/img-proxy -trimpath -ldflags "-X 'main.version=${SHA}'"
        name: Build Binary
        env:
          CGO_ENABLED: "0"

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
        with:
          images: ghcr.io/bangumi/img-proxy
          tags: |
            type=ref,event=branch
            type=ref,event=branch,suffix=-${{ env.SHA }}

      - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          provenance: false
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
