name: release

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          cache: true

      - run: echo "SHA=$(git show --no-patch --no-notes --date=short-local --pretty='%as-%h')" >> $GITHUB_ENV
        env:
          TZ: UTC

      - run: go build -o dist/img-proxy -trimpath -ldflags "-X 'main.version=${SHA}'"
        name: Build Binary
        env:
          CGO_ENABLED: "0"

      - run: docker build -t ghcr.io/bangumi/img-proxy:${{env.SHA}} .

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - run: docker push ghcr.io/bangumi/img-proxy:${{env.SHA}}
